'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'dist');
// Local configuration is ignored by Git. Vercel supplies the variable at build time.
const localEnv = path.join(root, '.env.local');
if (fs.existsSync(localEnv)) process.loadEnvFile(localEnv);
const accessKey = process.env.WEB3FORMS_ACCESS_KEY?.trim() || '';
// Explicit public allowlist: environment files, tests and documentation never
// enter static output. Only the Web3Forms public form key is injected below.
const publicFiles = [
    'index.html', 'project.html', 'style.css', 'project.css', 'content.js',
    'content-renderer.js', 'script.js', 'contact.js', 'project.js',
    'hero-motion.js', 'atmosphere.js', 'foto-james.png', 'assets'
];
fs.rmSync(output, { recursive: true, force: true });
fs.mkdirSync(output);
for (const file of publicFiles) fs.cpSync(path.join(root, file), path.join(output, file), { recursive: true });
// Optional transcript: only expose the row when the configured local asset is
// present and has a PDF header. Never create a placeholder academic document.
const contentSource = fs.readFileSync(path.join(root, 'content.js'), 'utf8');
const contentContext = { window: {} };
vm.runInNewContext(contentSource, contentContext, { timeout: 1000 });
const transcriptPath = contentContext.window.portfolioContent?.transcriptUrl;
let transcriptAvailable = false;
if (typeof transcriptPath === 'string' && /^assets\/.+\.pdf$/i.test(transcriptPath)) {
    const assetsRoot = path.join(root, 'assets') + path.sep;
    const candidate = path.resolve(root, transcriptPath);
    let descriptor;
    try {
        if (candidate.startsWith(assetsRoot) && fs.realpathSync(candidate).startsWith(assetsRoot) && fs.statSync(candidate).isFile()) {
            descriptor = fs.openSync(candidate, 'r');
            const signature = Buffer.alloc(5);
            transcriptAvailable = fs.readSync(descriptor, signature, 0, 5, 0) === 5 && signature.toString('ascii') === '%PDF-';
        }
    } catch { /* Absent or unreadable optional PDF: leave the row hidden. */ }
    finally { if (descriptor !== undefined) fs.closeSync(descriptor); }
}
fs.appendFileSync(path.join(output, 'content.js'), `\n// Availability is generated by the build; configure transcriptUrl in source.\nwindow.portfolioContent.transcriptAvailable = ${transcriptAvailable};\n`);
const indexPath = path.join(output, 'index.html');
const index = fs.readFileSync(indexPath, 'utf8');
const keyInput = '<input type="hidden" id="contact-access-key" name="access_key" value="">';
if (!index.includes(keyInput)) throw new Error('Missing Web3Forms access-key input in index.html');
const escapedKey = accessKey.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
fs.writeFileSync(indexPath, index.replace(keyInput, () => keyInput.replace('value=""', () => `value="${escapedKey}"`)));
if (!accessKey) console.warn('WEB3FORMS_ACCESS_KEY is unset. Configure it and rebuild before using Contact.');
console.log('Static build complete. Contact submits directly to Web3Forms.');
